version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aaaaaa1
      POSTGRES_DB: croncrm
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aaaaaa1
      POSTGRES_DB: croncrm
    networks:
      - freecodecamp
networks:
  freecodecamp: